[package]
name = "obsrv-api"
version = "0.1.0"
edition = "2024"

[dependencies]
obsrv-core = { path = "../obsrv-core"}
tower-http = { version = "0.5.2", features = ["cors"] }
reqwest = {version = "0.12.28", features = ["json"]}
axum = { version = "0.7.9", features = ["ws"] }
base64 = "0.22.1"
bs58 = "0.5.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
dotenvy = "0.15"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
helius = "1.1.0"
solana-sdk = "3.0"
solana-transaction-status = "3.1.14"
solana-client = "3.1.14"

sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "chrono", "uuid", "migrate"]}

chrono = { version = "0.4", features = ["serde"] }
